trigger:
  branches:
    include:
    - master
  paths:
    include:
    - OnlyShare.Client
variables:
- name: buildConfiguration
  value: 'Release'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: windows-latest
    steps:
    - task: UseDotNet@2
      displayName: Use Dotnet 7
      inputs:
        version: "7.0.x"
    - task: NuGetToolInstaller@0
      displayName: "Install NuGet"
      inputs:
        versionSpec: 6.0.x
        checkLatest: true
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore'
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: CmdLine@2
      displayName: "Dotnet build OnlyShare.Client"
      inputs:
        script: dotnet build Client/OnlyShare.Client.csproj -o $(Build.ArtifactStagingDirectory) --configuration Release /p:EnvironmentName=Development

